password_requirements:
  blacklist:
  - password
  - ThisIsOuter1234!!
  - '123456'
  - qwerty
  - admin
  - letmein
  - welcome
  - monkey
  - '1234567890'
  - password123
  - abc123
  - '111111'
  - '123123'
  - admin123
  - root
  - user
  - guest
  - test
  - demo
  - sample
  custom_regex: null
  digits: true
  history_count: 3
  lockout_duration_minutes: 15
  lowercase: true
  max_login_attempts: 3
  min_length: 10
  special: true
  uppercase: true

# NEW: Policy messages for user feedback
policy_message:
  non_compliant_message: "Your current password no longer meets our updated security policy. For your account security, please update your password now."
  requirements_message: "Password must contain at least {min_length} characters including {requirements}. It cannot match common passwords or your previous {history_count} passwords."